# Generated by Django 5.2 on 2026-01-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('hashed_token', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'URL Shortener',
                'verbose_name_plural': 'URL Shortener List',
                'db_table': 'url_shortener',
            },
        ),
    ]
